export const loot = [
  {
    id: 1,
    name: "Armadyl Helmet",
    droprate: "1/381",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 2,
    name: "Armadyl Chestplate",
    droprate: "1/381",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 3,
    name: "Armadyl Chainskirt",
    droprate: "1/381",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 4,
    name: "Armadyl Hilt",
    droprate: "1/508",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 5,
    name: "Godsword Shard 1",
    droprate: "1/762",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 6,
    name: "Godsword Shard 2",
    droprate: "1/762",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 7,
    name: "Godsword Shard 3",
    droprate: "1/762",
    killcount: 0,
    date: "",
    achieved: false,
  },
];
