const meleeEquipment = [
  {
    id: 1,
    image:
      "https://oldschool.runescape.wiki/images/Helm_of_neitiznot.png?28729",
    tier: "D",
    name: "Helm of Neitiznot",
    achieved: false,
  },
  {
    id: 2,
    image: "https://oldschool.runescape.wiki/images/Dragon_scimitar.png?cc5f3",
    tier: "D",
    name: "Dragon Scimitar",
    achieved: false,
  },
  {
    id: 3,
    image: "https://oldschool.runescape.wiki/images/Sarachnis_cudgel.png?c4e91",
    tier: "C",
    name: "Sarachnis Cudgel",
    achieved: false,
  },
  {
    id: 4,
    image: "https://oldschool.runescape.wiki/images/Saradomin_sword.png?c943f",
    tier: "C",
    name: "Saradomin Sword",
    achieved: false,
  },
  {
    id: 5,
    image: "https://oldschool.runescape.wiki/images/Dragon_boots.png?c85b3",
    tier: "C",
    name: "Dragon Boots",
    achieved: false,
  },
  {
    id: 6,
    image: "https://oldschool.runescape.wiki/images/Barrows_gloves.png?3be33",
    tier: "C",
    name: "Barrows Gloves",
    achieved: false,
  },
  {
    id: 7,
    image: "https://oldschool.runescape.wiki/images/Warrior_ring.png?75a26",
    tier: "C",
    name: "Warrior Ring",
    achieved: false,
  },
  {
    id: 8,
    image: "https://oldschool.runescape.wiki/images/Berserker_ring.png?3be33",
    tier: "C",
    name: "Berserker Ring",
    achieved: false,
  },
  {
    id: 9,
    image: "https://oldschool.runescape.wiki/images/Fire_cape.png?5abba",
    tier: "C",
    name: "Fire Cape",
    achieved: false,
  },
  {
    id: 10,
    image: "https://oldschool.runescape.wiki/images/Abyssal_whip.png?727e9",
    tier: "B",
    name: "Abyssal Whip",
    achieved: false,
  },
  {
    id: 11,
    image: "https://oldschool.runescape.wiki/images/Dragon_defender.png?3a184",
    tier: "B",
    name: "Dragon Defender",
    achieved: false,
  },
  {
    id: 12,
    image: "https://oldschool.runescape.wiki/images/Amulet_of_fury.png?248b4",
    tier: "B",
    name: "Amulet of Fury",
    achieved: false,
  },
  {
    id: 13,
    image: "https://oldschool.runescape.wiki/images/Guardian_boots.png?d316a",
    tier: "B",
    name: "Guardian Boots",
    achieved: false,
  },
  {
    id: 14,
    image: "https://oldschool.runescape.wiki/images/Serpentine_helm.png?c82f9",
    tier: "B",
    name: "Serpentine Helm",
    achieved: false,
  },
  {
    id: 15,
    image:
      "https://oldschool.runescape.wiki/images/Blessed_spirit_shield.png?31e5c",
    tier: "B",
    name: "Blessed Spirit Shield",
    achieved: false,
  },
  {
    id: 16,
    image: "https://oldschool.runescape.wiki/images/Abyssal_dagger.png?c04be",
    tier: "B",
    name: "Abyssal Dagger",
    achieved: false,
  },
  {
    id: 17,
    image: "https://oldschool.runescape.wiki/images/Armadyl_godsword.png?e56f0",
    tier: "B",
    name: "Armadyl Godsword",
    achieved: false,
  },
  {
    id: 18,
    image: "https://oldschool.runescape.wiki/images/Zamorak_godsword.png?faa5d",
    tier: "B",
    name: "Zamorak Godsword",
    achieved: false,
  },
  {
    id: 19,
    image: "https://oldschool.runescape.wiki/images/Zamorakian_hasta.png?37c64",
    tier: "B",
    name: "Zamorakian Hasta",
    achieved: false,
  },
  {
    id: 20,
    image: "https://oldschool.runescape.wiki/images/Zamorakian_spear.png?420f4",
    tier: "B",
    name: "Zamorakian Spear",
    achieved: false,
  },
  {
    id: 21,
    image: "https://oldschool.runescape.wiki/images/Dinh%27s_bulwark.png?2c9d4",
    tier: "B",
    name: "Dinh's Bulwark",
    achieved: false,
  },
  {
    id: 22,
    image: "https://oldschool.runescape.wiki/images/Elder_maul.png?0a875",
    tier: "B",
    name: "Elder Maul",
    achieved: false,
  },
  {
    id: 23,
    image: "https://oldschool.runescape.wiki/images/Dragon_claws.png?c85b3",
    tier: "B",
    name: "Dragon Claws",
    achieved: false,
  },
  {
    id: 24,
    image:
      "https://oldschool.runescape.wiki/images/Dragonfire_shield_%28uncharged%29.png?8fa13",
    tier: "A",
    name: "Dragonfire Shield",
    achieved: false,
  },
  {
    id: 25,
    image: "https://oldschool.runescape.wiki/images/Primordial_boots.png?e2ec4",
    tier: "A",
    name: "Primordial Boots",
    achieved: false,
  },
  {
    id: 26,
    image: "https://oldschool.runescape.wiki/images/Abyssal_bludgeon.png?b10f5",
    tier: "A",
    name: "Abyssal Bludgeon",
    achieved: false,
  },
  {
    id: 27,
    image: "https://oldschool.runescape.wiki/images/Bandos_godsword.png?22c06",
    tier: "A",
    name: "Bandos Godsword",
    achieved: false,
  },
  {
    id: 28,
    image:
      "https://oldschool.runescape.wiki/images/Saradomin_godsword.png?11815",
    tier: "A",
    name: "Saradomin Godsword",
    achieved: false,
  },
  {
    id: 29,
    image: "https://oldschool.runescape.wiki/images/Dragon_warhammer.png?73103",
    tier: "A",
    name: "Dragon Warhammer",
    achieved: false,
  },
  {
    id: 30,
    image: "https://oldschool.runescape.wiki/images/Blade_of_saeldor.png?8a5fa",
    tier: "A",
    name: "Blade of Saeldor",
    achieved: false,
  },
  {
    id: 31,
    image:
      "https://oldschool.runescape.wiki/images/Amulet_of_torture.png?ec289",
    tier: "A",
    name: "Amulet of Torture",
    achieved: false,
  },
  {
    id: 32,
    image:
      "https://oldschool.runescape.wiki/images/Ring_of_suffering.png?dd602",
    tier: "A",
    name: "Ring of Suffering",
    achieved: false,
  },
  {
    id: 33,
    image:
      "https://oldschool.runescape.wiki/images/Bandos_chestplate.png?f928c",
    tier: "A",
    name: "Bandos Chestplate ",
    achieved: false,
  },
  {
    id: 34,
    image: "https://oldschool.runescape.wiki/images/Bandos_tassets.png?f928c",
    tier: "A",
    name: "Bandos Tassets",
    achieved: false,
  },
  {
    id: 35,
    image: "https://oldschool.runescape.wiki/images/Bandos_boots.png?f928c",
    tier: "A",
    name: "Bandos Boots",
    achieved: false,
  },
  {
    id: 36,
    image: "https://oldschool.runescape.wiki/images/Ghrazi_rapier.png?d2266",
    tier: "S",
    name: "Ghrazi Rapier",
    achieved: false,
  },
  {
    id: 37,
    image: "https://oldschool.runescape.wiki/images/Scythe_of_vitur.png?c943f",
    tier: "S",
    name: "Scythe of Vitur",
    achieved: false,
  },
  {
    id: 38,
    image:
      "https://oldschool.runescape.wiki/images/Justiciar_faceguard.png?fb842",
    tier: "S",
    name: "Justiciar Faceguard",
    achieved: false,
  },
  {
    id: 39,
    image:
      "https://oldschool.runescape.wiki/images/Justiciar_chestguard.png?fb842",
    tier: "S",
    name: "Justiciar Chestguard",
    achieved: false,
  },
  {
    id: 40,
    image:
      "https://oldschool.runescape.wiki/images/Justiciar_legguards.png?cff7a",
    tier: "S",
    name: "Justiciar Legguards",
    achieved: false,
  },
  {
    id: 41,
    image:
      "https://oldschool.runescape.wiki/images/Elysian_spirit_shield.png?1bc1e",
    tier: "S",
    name: "Elysian Spirit Shield",
    achieved: false,
  },
  {
    id: 42,
    image:
      "https://oldschool.runescape.wiki/images/Inquisitor%27s_mace.png?13f14",
    tier: "S",
    name: "Inquisitor's Mace",
    achieved: false,
  },
  {
    id: 43,
    image:
      "https://oldschool.runescape.wiki/images/Inquisitor%27s_great_helm.png?e75c0",
    tier: "S",
    name: "Inquisitor's Great Helm",
    achieved: false,
  },
  {
    id: 44,
    image:
      "https://oldschool.runescape.wiki/images/Inquisitor%27s_hauberk.png?19317",
    tier: "S",
    name: "Inquisitor's Hauberk",
    achieved: false,
  },
  {
    id: 45,
    image:
      "https://oldschool.runescape.wiki/images/Inquisitor%27s_plateskirt.png?19317",
    tier: "S",
    name: "Inquisitor's Plateskirt",
    achieved: false,
  },
  {
    id: 46,
    image:
      "https://oldschool.runescape.wiki/images/Dragon_hunter_lance.png?cc5f3",
    tier: "S",
    name: "Dragon Hunter Lance",
    achieved: false,
  },
  {
    id: 47,
    image: "https://oldschool.runescape.wiki/images/Torva_full_helm.png?1b66d",
    tier: "S+",
    name: "Torva Full Helm",
    achieved: false,
  },
  {
    id: 48,
    image: "https://oldschool.runescape.wiki/images/Torva_platebody.png?02c8a",
    tier: "S+",
    name: "Torva Platebody",
    achieved: false,
  },
  {
    id: 49,
    image: "https://oldschool.runescape.wiki/images/Torva_platelegs.png?d6504",
    tier: "S+",
    name: "Torva Platelegs",
    achieved: false,
  },
  {
    id: 50,
    image:
      "https://oldschool.runescape.wiki/images/Osmumten%27s_fang.png?b0b20",
    tier: "S+",
    name: "Osmumten's Fang",
    achieved: false,
  },
  {
    id: 51,
    image: "https://oldschool.runescape.wiki/images/Avernic_defender.png?e4676",
    tier: "S+",
    name: "Avernic Defender",
    achieved: false,
  },
  {
    id: 52,
    image: "https://oldschool.runescape.wiki/images/Infernal_cape.png?80b36",
    tier: "S+",
    name: "Infernal Cape",
    achieved: false,
  },
];

export default meleeEquipment;
