export const loot = [
  {
    id: 1,
    name: "Steam Battlestaff",
    droprate: "1/127",
    killcount: 0,
    achieved: false,
  },
  {
    id: 2,
    name: "Zamorakian Spear",
    droprate: "1/127",
    killcount: 0,
    achieved: false,
  },
  {
    id: 3,
    name: "Staff of the Dead",
    droprate: "1/508",
    killcount: 0,
    achieved: false,
  },
  {
    id: 4,
    name: "Zamorak Hilt",
    droprate: "1/508",
    killcount: 0,
    achieved: false,
  },
  {
    id: 5,
    name: "Godsword Shard 1",
    droprate: "1/762",
    killcount: 0,
    achieved: false,
  },
  {
    id: 6,
    name: "Godsword Shard 2",
    droprate: "1/762",
    killcount: 0,
    achieved: false,
  },
  {
    id: 7,
    name: "Godsword Shard 3",
    droprate: "1/762",
    killcount: 0,
    achieved: false,
  },
];
