export const loot = [
  {
    id: 1,
    name: "Warrior Ring",
    droprate: "1/128",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 2,
    name: "Berserker Ring",
    droprate: "1/128",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 3,
    name: "Archer's Ring",
    droprate: "1/128",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 4,
    name: "Seers' Ring",
    droprate: "1/128",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 5,
    name: "Mud Battlestaff",
    droprate: "1/128",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 6,
    name: "Dragon Axe",
    droprate: "1/128",
    killcount: 0,
    date: "",
    achieved: false,
  },
];
