export const loot = [
  {
    id: 1,
    name: "Saradomin Sword",
    droprate: "1/381",
    killcount: 0,
    achieved: false,
  },
  {
    id: 2,
    name: "Saradomin's Light",
    droprate: "1/254",
    killcount: 0,
    achieved: false,
  },
  {
    id: 3,
    name: "Armadyl Crossbow",
    droprate: "1/508",
    killcount: 0,
    achieved: false,
  },
  {
    id: 4,
    name: "Saradomin Hilt",
    droprate: "1/508",
    killcount: 0,
    achieved: false,
  },
  {
    id: 5,
    name: "Godsword Shard 1",
    droprate: "1/762",
    killcount: 0,
    achieved: false,
  },
  {
    id: 6,
    name: "Godsword Shard 2",
    droprate: "1/762",
    killcount: 0,
    achieved: false,
  },
  {
    id: 7,
    name: "Godsword Shard 3",
    droprate: "1/762",
    killcount: 0,
    achieved: false,
  },
];
