export const bossLoot = {
  barrows: [
    {
      id: 1,
      name: "Ahrim's Hood",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 2,
      name: "Ahrim's Robetop",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 3,
      name: "Ahrim's Robeskirt",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 4,
      name: "Ahrim's Staff",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 5,
      name: "Dharok's Helm",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 6,
      name: "Dharok's Platebody",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 7,
      name: "Dharok's Platelegs",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 8,
      name: "Dharok's Greataxe",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 9,
      name: "Guthan's Helm",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 10,
      name: "Guthan's Platebody",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 11,
      name: "Guthan's Chainskirt",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 12,
      name: "Guthan's Warspear",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 13,
      name: "Karil's Coif",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 14,
      name: "Karil's Leathertop",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 15,
      name: "Karil's Leatherskirt",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 16,
      name: "Karil's Crossbow",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 17,
      name: "Torag's Helm",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 18,
      name: "Torag's Platebody",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 19,
      name: "Torag's Platelegs",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 20,
      name: "Torag's Hammers",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 21,
      name: "Verac's Helm",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 22,
      name: "Verac's Brassard",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 23,
      name: "Verac's Plateskirt",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
    {
      id: 24,
      name: "Verac's Flail",
      droprate: "1/16.5",
      killcount: 0,
      achieved: false,
    },
  ],
  commanderZilyana: [
    {
      id: 1,
      name: "Saradomin Sword",
      droprate: "1/381",
      killcount: 0,
      achieved: false,
    },
    {
      id: 2,
      name: "Saradomin's Light",
      droprate: "1/254",
      killcount: 0,
      achieved: false,
    },
    {
      id: 3,
      name: "Armadyl Crossbow",
      droprate: "1/508",
      killcount: 0,
      achieved: false,
    },
    {
      id: 4,
      name: "Saradomin Hilt",
      droprate: "1/508",
      killcount: 0,
      achieved: false,
    },
    {
      id: 5,
      name: "Godsword Shard 1",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
    {
      id: 6,
      name: "Godsword Shard 2",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
    {
      id: 7,
      name: "Godsword Shard 3",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
  ],
  corporealBeast: [
    {
      id: 1,
      name: "Spectral Sigil",
      droprate: "1/1365",
      killcount: 0,
      achieved: false,
    },
    {
      id: 2,
      name: "Arcane Sigil",
      droprate: "1/1365",
      killcount: 0,
      achieved: false,
    },
    {
      id: 3,
      name: "Elysian Sigil",
      droprate: "1/4095",
      killcount: 0,
      achieved: false,
    },
    {
      id: 4,
      name: "Spirit Shield",
      droprate: "1/64",
      killcount: 0,
      achieved: false,
    },
    {
      id: 5,
      name: "Holy Elixir",
      droprate: "1/170.7",
      killcount: 0,
      achieved: false,
    },
  ],
  dagannothPrime: [
    {
      id: 1,
      name: "Warrior Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 2,
      name: "Berserker Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 3,
      name: "Archer's Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 4,
      name: "Seers' Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 5,
      name: "Mud Battlestaff",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 6,
      name: "Dragon Axe",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
  ],
  dagannothRex: [
    {
      id: 1,
      name: "Warrior Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 2,
      name: "Berserker Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 3,
      name: "Archer's Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 4,
      name: "Seers' Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 5,
      name: "Mud Battlestaff",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 6,
      name: "Dragon Axe",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
  ],
  dagannothSupreme: [
    {
      id: 1,
      name: "Warrior Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 2,
      name: "Berserker Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 3,
      name: "Archer's Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 4,
      name: "Seers' Ring",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 5,
      name: "Mud Battlestaff",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 6,
      name: "Dragon Axe",
      droprate: "1/128",
      killcount: 0,
      date: "",
      achieved: false,
    },
  ],
  generalGraardor: [
    {
      id: 1,
      name: "Bandos Chestplate",
      droprate: "1/381",
      killcount: 0,
      achieved: false,
    },
    {
      id: 2,
      name: "Bandos Tassets",
      droprate: "1/381",
      killcount: 0,
      achieved: false,
    },
    {
      id: 3,
      name: "Bandos Boots",
      droprate: "1/381",
      killcount: 0,
      achieved: false,
    },
    {
      id: 4,
      name: "Bandos Hilt",
      droprate: "1/508",
      killcount: 0,
      achieved: false,
    },

    {
      id: 5,
      name: "Godsword Shard 1",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
    {
      id: 6,
      name: "Godsword Shard 2",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
    {
      id: 7,
      name: "Godsword Shard 3",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
  ],
  kreeArra: [
    {
      id: 1,
      name: "Bandos Chestplate",
      droprate: "1/381",
      killcount: 0,
      achieved: false,
    },
    {
      id: 2,
      name: "Bandos Tassets",
      droprate: "1/381",
      killcount: 0,
      achieved: false,
    },
    {
      id: 3,
      name: "Bandos Boots",
      droprate: "1/381",
      killcount: 0,
      achieved: false,
    },
    {
      id: 4,
      name: "Bandos Hilt",
      droprate: "1/508",
      killcount: 0,
      achieved: false,
    },

    {
      id: 5,
      name: "Godsword Shard 1",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
    {
      id: 6,
      name: "Godsword Shard 2",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
    {
      id: 7,
      name: "Godsword Shard 3",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
  ],
  krilTsutsaroth: [
    {
      id: 1,
      name: "Steam Battlestaff",
      droprate: "1/127",
      killcount: 0,
      achieved: false,
    },
    {
      id: 2,
      name: "Zamorakian Spear",
      droprate: "1/127",
      killcount: 0,
      achieved: false,
    },
    {
      id: 3,
      name: "Staff of the Dead",
      droprate: "1/508",
      killcount: 0,
      achieved: false,
    },
    {
      id: 4,
      name: "Zamorak Hilt",
      droprate: "1/508",
      killcount: 0,
      achieved: false,
    },
    {
      id: 5,
      name: "Godsword Shard 1",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
    {
      id: 6,
      name: "Godsword Shard 2",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
    {
      id: 7,
      name: "Godsword Shard 3",
      droprate: "1/762",
      killcount: 0,
      achieved: false,
    },
  ],
  nex: [
    {
      id: 1,
      name: "Zaryte Vambraces",
      droprate: "1/172",
      killcount: 0,
      achieved: false,
    },
    {
      id: 2,
      name: "Nihil Horn",
      droprate: "1/258",
      killcount: 0,
      achieved: false,
    },
    {
      id: 3,
      name: "Torva Full Helm (damaged)",
      droprate: "1/258",
      killcount: 0,
      achieved: false,
    },
    {
      id: 4,
      name: "Torva Platebody (damaged)",
      droprate: "1/258",
      killcount: 0,
      achieved: false,
    },
    {
      id: 5,
      name: "Torva Platelegs (damaged)",
      droprate: "1/258",
      killcount: 0,
      achieved: false,
    },
    {
      id: 6,
      name: "Ancient Hilt",
      droprate: "1/516",
      killcount: 0,
      achieved: false,
    },
  ],
  sarachnis: [
    {
      id: 1,
      name: "Sarachnis Cudgel",
      droprate: "1/384",
      killcount: 0,
      date: "",
      achieved: false,
    },
  ],
  zulrah: [
    {
      id: 1,
      name: "Tanzanite Fang",
      droprate: "1/512",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 2,
      name: "Magic Fang",
      droprate: "1/512",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 3,
      name: "Serpentine Visage",
      droprate: "1/512",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 4,
      name: "Tanzanite Mutagen",
      droprate: "1/6553",
      killcount: 0,
      date: "",
      achieved: false,
    },
    {
      id: 5,
      name: "Magma Mutagen",
      droprate: "1/6553",
      killcount: 0,
      date: "",
      achieved: false,
    },
  ],
};
