export const loot = [
  {
    id: 1,
    name: "Tanzanite Fang",
    droprate: "1/512",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 2,
    name: "Magic Fang",
    droprate: "1/512",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 3,
    name: "Serpentine Visage",
    droprate: "1/512",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 4,
    name: "Tanzanite Mutagen",
    droprate: "1/6553",
    killcount: 0,
    date: "",
    achieved: false,
  },
  {
    id: 5,
    name: "Magma Mutagen",
    droprate: "1/6553",
    killcount: 0,
    date: "",
    achieved: false,
  },
];
